---
- name: Install Terminal Applications
  hosts: terminal
  vars_files:
    - default.terminal.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:

    # extra-packages should go after universe to ensure packages are found
    - name: Install extra apt, pip, pipx, and gem packages
      ansible.builtin.import_tasks: tasks/extra-packages.yml
