---
- name: Configure Debian repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb https://deb.debian.org/debian/ {{ ansible_distribution_release | lower }} main contrib non-free non-free-firmware"
    - "deb https://deb.debian.org/debian-security {{ ansible_distribution_release | lower }}-security main contrib non-free non-free-firmware"
    - "deb https://deb.debian.org/debian/ {{ ansible_distribution_release | lower }}-updates main contrib non-free non-free-firmware"
    - "deb https://deb.debian.org/debian/ {{ ansible_distribution_release | lower }}-backports main contrib non-free non-free-firmware"
