---

- name: Clone the dotfiles repository
  git:
    repo: https://github.com/jorkle/dotfiles.git
    dest: /home/jorkle/.dotfiles
    clone: yes
    update: yes

- name: Install dotfiles
  ansible.builtin.shell:
    chdir: /home/jorkle/.dotfiles
    cmd: "./install"
