---
- name: Install global apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ apt_desktop_packages }}"
