---
- name: Install global apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ apt_packages }}"

- name: Install global Pip packages.
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    break_system_packages: true
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ pip_packages }}"

- name: Install global Pipx packages.
  community.general.pipx:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  loop: "{{ pipx_packages }}"

- name: Install global Ruby gems.
  become: true
  community.general.gem:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    user_install: false
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ gem_packages }}"
