---
- name: Install flatpak packages
  become: true
  ansible.builtin.apt:
    name:
      - "gnome-software"
      - "gnome-software-plugin-flatpak"
    state: present

- name: Install flatpak packages
  become: true
  ansible.builtin.apt:
    name: "flatpak"
    state: present
  when: configure_flatpak_gnome_software

- name: Install flatpak remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak Applications
  become: true
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  with_items: "{{ flatpaks }}"
