---
- name: Install Spotify apt repository gpg key
  become: true
  ansible.builtin.shell: 
    cmd: "curl -sS https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg | gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg"
- name: Configure Spotify apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
- name: Update apt repositories
  become: true
  ansible.builtin.apt:
    update_cache: yes
- name: Install spotify-client
  become: true
  ansible.builtin.apt:
    name: spotify-client
