---
- name: Get latest release of a public repository
  community.general.github_release:
    user: ulauncher
    repo: ulauncher
    action: latest_release
  register: ulauncher_latest

- name: Install deb from github (Specific Version)
  become: true
  ansible.builtin.apt:
    deb: >-
        https://github.com/Ulauncher/Ulauncher/releases/download/{{ ulauncher_version }}/ulauncher_{{ ulauncher_version }}_all.deb
  when: ulauncher_version is defined

- name: Install deb from github (Latest)
  become: true
  ansible.builtin.apt:
    deb: >-
        https://github.com/Ulauncher/Ulauncher/releases/download/{{ ulauncher_latest.tag }}/ulauncher_{{ ulauncher_latest.tag }}_all.deb
  when: ulauncher_version is not defined
